### ISSUE TITLE
Investigate why custom fonts don't pick up font weight

### ISSUE THREAD

**Issue by mauriceschenk** [steamclock/niceComponents#66]
It looks like that some recent changes messed up the font weight being applied to custom (maybe all) fonts. More context can be found in this [Slack thread](https://steamclock.slack.com/archives/C0302CZ1QG4/p1727202906592069).

**Comment by dayvauld** [comment]
It seems that from the change here, https://github.com/steamclock/niceComponents/pull/64/files, it fixed the issue that weights were not getting set for custom fonts. 

And I should note that if font weight is not specified when initializing/configuring a style, it will default to `.regular`.
https://github.com/steamclock/niceComponents/blob/4eabb66f80be26616e8b252179ba4fa9882d86a0/Sources/NiceComponents/Text/NiceTextStyle.swift#L24

So from my inspection of the project in question's codebase, it seems that we are using static font files (ie. `"FontFamily-Medium"`) and then by default initialization the weight is set to `.regular`. This thinner weight is then applied to the font which then thins out the text. 

I'm not entirely sure if SwiftUI's Font is modifying/shrinking the static font from `"medium"` to `"regular"` to make it thinner or it is doing some sort of behind the scenes magic to find the corresponding weight file in the family. The documentation is quite sparse on how weights are handled.

With that being said, I see a few possible ways forward:
1) Add a font file type enum for static and variable fonts in `NiceTextStyle`, and when a custom static font is used we don't apply the weight modification.
2) Fix the project that has an issue with this NiceComponents version to use the font family name (ie. `scaledFont(name: "Helvetica")`, not `scaledFont(name: "Helvetica-Medium")`) and explicitly set the weights (ie. `.with(weight: .medium)`)
3) Fix the project that has an issue with this NiceComponents version by replacing the static font files with the single dynamic font file and then explicitly set the weights for the various text styles.

Of course, I might be missing something here as I am new to this library and do not have a lot of in-depth experience with custom font handling.

**Comment by brendanlensink** [comment]
Thanks for the insight Dave! Sounds like [this fix](https://github.com/steamclock/niceComponents/pull/64/files) actually caused the other app the break, so I think it makes the most sense to go with option #2 and go ahead and fix that there. 

Going to go ahead and close this then, as it seems like NC is behaving as it should.
